drivers: misc: mediatek: perf_common: add missing function prototypes
../drivers/misc/mediatek/perf_common/perf_tracker.c:56:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_vcore_uv()
                                          ^
                                           void
../drivers/misc/mediatek/perf_common/perf_tracker.c:61:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_ddr_khz()
                                         ^
                                          void
2 errors generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>